### ISSUE TITLE
Scanned image is not in color

### ISSUE THREAD

**Issue by debiantriage** [kno10/python-scan-eSCL#4]
This was done on Debian stable (stretch) but unstable has the same outcome. test.jpg is not in colour. A log is attached.

  python scan.py test.jpg 300

[logg.txt](https://github.com/kno10/python-scan-eSCL/files/2742204/logg.txt)

  curl -v -X POST -d @$1 http://192.168.7.235:8080/eSCL/ScanJobs

does produce an image in color. The settings file ($1) is attached.

[scansettings-300.xml.txt](https://github.com/kno10/python-scan-eSCL/files/2742232/scansettings-300.xml.txt)

Regards,

Brian.

**Comment by debiantriage** [comment]
Oops!

My color image was produced with <pwg:InputSource>Platen</pwg:InputSource> in the settings file. That's the trouble with testing and forgetting file alterations,

-- 
Brian.

**Comment by kno10** [comment]
With different scanners you probably need to play around with the settings. For example, try setting the mode to Photo - maybe it defaults to Text, and only uses grayscale in that mode.

As I only have a single printer I cannot test compatibilities. This is someone elses job; I only provide this prototype that worked with my printer. Anyone is open to pick this code up and develop it into a real application (or rather, I would suggest to develop an eSCL backend for SANE).

**Comment by debiantriage** [comment]
Thank you for the informative reply, Erich. The issue is resolved with

etree.SubElement(req, "{%s}InputSource" % pwgns).text = "Platen"

What device did you prototype?

Incidenrally, SCL is Scanner Control Language. What does the "e" in "eSCL" stand for? Enhanced? Extended? Embedded?

-- 
Brian.

**Comment by kno10** [comment]
I don't know what the e is for.
