### ISSUE TITLE
A GUI for scanning

### ISSUE THREAD

**Issue by markosjal** [kno10/python-scan-eSCL#5]
I just wanted to share this as you mention the need for a GUI . It should be fairly easy to modify for your Python code as it activates a command line for all functions. If I had one of those scanners, I think it would be easy for me to modify the code.

Coincidently its called AirScan, I had no idea that Apple used "AirScan"

info: http://teknogeekz.com/#projects
download: http://teknogeekz.com/downloads/AirScan7.0Free.zip

I am not a real coder I just filled a need that I and others had with some php skills that I have learned along the way. It is messy in places.  

If you activate the paid version options in config file it will show more options in the GUI

I borrowed from phpSANE and other projects, and offer it for your use.

let me know if there is anything I can do to help if you want to use it. Also I have a newer version with more imagemagick options if interested.

Finding this makes me wonder if I should make a generic scanner command line front-end with customizable commands. It seems I am close already and can add all comands to the config file, and add more settings / commands if necessary.

I think ultimately what is needed is a SANE to command line backend that can execute a custom command line  for projects like yours.

Mark
markosjal  at gmail

**Comment by kno10** [comment]
Please, no advertisement for non-open-source here
